repos:
  # Hooks JavaScript/TypeScript
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.44.0
    hooks:
      - id: eslint
        files: \.(js|jsx|ts|tsx)$
        types: [file]
        additional_dependencies:
          - eslint@8.44.0
          - '@typescript-eslint/eslint-plugin@6.0.0'
          - '@typescript-eslint/parser@6.0.0'
          - eslint-plugin-react@7.32.2
          - eslint-plugin-react-hooks@4.6.0
          - eslint-plugin-jsx-a11y@6.7.1

  # Prettier - Formatage JavaScript/TypeScript
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.0
    hooks:
      - id: prettier
        files: \.(js|jsx|ts|tsx|json|css|scss|md|yaml|yml)$

  # Hooks Git
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: check-added-large-files
      - id: check-json
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  # Hooks spécifiques au frontend
  - repo: local
    hooks:
      - id: frontend-test-quick
        name: Frontend quick tests
        entry: npm run test:ci
        language: system
        pass_filenames: false
        always_run: true
        stages: [push]

      - id: frontend-build-check
        name: Frontend build check
        entry: npm run build
        language: system
        pass_filenames: false
        always_run: true
        stages: [push]
